#========================================================================
# Copyright 2022 Rodrigo Laiola Guimaraes
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

version: '3.8'

services:

    traefik:
        image: "traefik:v2.6"
        container_name: "traefik"
        restart: unless-stopped
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        networks:                                                                                                                              
            - traefik-proxy
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
            - "traefik.http.routers.traefik.entrypoints=web"
            - "traefik.http.routers.traefik.service=api@internal"

    portainer:
        image: portainer/portainer-ce:2.0.0
        container_name: "portainer"
        command: -H unix:///var/run/docker.sock
        restart: unless-stopped
        networks:                                                                                                                              
            - traefik-proxy 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        labels:
            # Frontend
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
            - "traefik.http.routers.portainer.entrypoints=web"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
            - "traefik.http.routers.portainer.service=portainer"

volumes:
    portainer_data:

networks:
    traefik-proxy:
        external: true
